### PR TITLE
UI for Installer Script

### PR DESCRIPTION
**Pull request by officiallygod**
## Proposed changes

https://jira.newfold.com/browse/PRESS0-2279

Added a hook as well to enqueue all the changes: **newfold/installer/enqueue_scripts**
Screenshot 2024-10-14 at 17 45 38

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [x] I have viewed my change in a web-browser
- [x] Linting and tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
I merged this into the `solutions` branch to create a `1.2.0-beta.2` release from that branch.

**Comment by officiallygod** [comment]
> I merged this into the `solutions` branch to create a `1.2.0-beta.2` release from that branch.

Looks Good

**Comment by wpscholar** [comment]
Closing this as it was merged into `solutions` branch already and isn't meant to be merged to main just yet.

**Comment by officiallygod** [comment]
> Closing this as it was merged into `solutions` branch already and isn't meant to be merged to main just yet.

Please ensure all the changes in this branch are incorporated as this has changes for [PRESS0-2298](https://jira.newfold.com/browse/PRESS0-2298) as well

**Comment by circlecube** [comment]
Reopened this to target the `solutions` branch and ensure all changes were included.

**Comment by circlecube** [comment]
Looks like everything was already included. Closing again.

**Comment by circlecube** [comment]
@officiallygod can you review these commits made after the branch was already merged?
- [some changes](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/dc31ebb1ef4e8b3dc50c1346c5b47c6ddfa09124)
- [build](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/bfff68db74595960ce253f7cab9da74943742771)
- [Changes](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/6f77937b468ed8384d9c5a7c975e91b5dea17823)

It would be best to make these in a fresh branch from `solutions` and submit in PR please.

**Comment by officiallygod** [comment]
> @officiallygod can you review these commits made after the branch was already merged?
> 
> * [some changes](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/dc31ebb1ef4e8b3dc50c1346c5b47c6ddfa09124)
> * [build](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/bfff68db74595960ce253f7cab9da74943742771)
> * [Changes](https://github.com/newfold-labs/wp-module-installer/pull/25/commits/6f77937b468ed8384d9c5a7c975e91b5dea17823)
> 
> It would be best to make these in a fresh branch from `solutions` and submit in PR please.

Sure @circlecube let me check things once and as a lot of things have changed, I will make a PR for the bugs mentioned by Micah as well from the `Solutions` branch

**Pull request closed without merging**
